p8105_hw2_ys3637
================
2022-10-03

``` r
# library all packages that we need at the beginning
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
    ## ✔ ggplot2 3.3.6      ✔ purrr   0.3.4 
    ## ✔ tibble  3.1.8      ✔ dplyr   1.0.10
    ## ✔ tidyr   1.2.0      ✔ stringr 1.4.1 
    ## ✔ readr   2.1.2      ✔ forcats 0.5.2 
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()

``` r
library(dplyr)
```

## Problem 1

This problem focuses on NYC Transit data; in particular, this CSV file
contains information related to each entrance and exit for each subway
station in NYC. If you’re not familiar with the NYC subway system,
keeping a map in mind while looking at these data might help.

### a)

Read and clean the data; retain line, station, name, station latitude /
longitude, routes served, entry, vending, entrance type, and ADA
compliance. Convert the entry variable from character (YES vs NO) to a
logical variable (the ifelse or recode function may be useful).

``` r
# read in data from CSV file
NYC_Transit <- read_csv("data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv")
```

    ## Rows: 1868 Columns: 32
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (22): Division, Line, Station Name, Route1, Route2, Route3, Route4, Rout...
    ## dbl  (8): Station Latitude, Station Longitude, Route8, Route9, Route10, Rout...
    ## lgl  (2): ADA, Free Crossover
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
# show the first several lines of the original data
head(NYC_Transit)
```

    ## # A tibble: 6 × 32
    ##   Division Line     Station…¹ Stati…² Stati…³ Route1 Route2 Route3 Route4 Route5
    ##   <chr>    <chr>    <chr>       <dbl>   <dbl> <chr>  <chr>  <chr>  <chr>  <chr> 
    ## 1 BMT      4 Avenue 25th St      40.7   -74.0 R      <NA>   <NA>   <NA>   <NA>  
    ## 2 BMT      4 Avenue 25th St      40.7   -74.0 R      <NA>   <NA>   <NA>   <NA>  
    ## 3 BMT      4 Avenue 36th St      40.7   -74.0 N      R      <NA>   <NA>   <NA>  
    ## 4 BMT      4 Avenue 36th St      40.7   -74.0 N      R      <NA>   <NA>   <NA>  
    ## 5 BMT      4 Avenue 36th St      40.7   -74.0 N      R      <NA>   <NA>   <NA>  
    ## 6 BMT      4 Avenue 45th St      40.6   -74.0 R      <NA>   <NA>   <NA>   <NA>  
    ## # … with 22 more variables: Route6 <chr>, Route7 <chr>, Route8 <dbl>,
    ## #   Route9 <dbl>, Route10 <dbl>, Route11 <dbl>, `Entrance Type` <chr>,
    ## #   Entry <chr>, `Exit Only` <chr>, Vending <chr>, Staffing <chr>,
    ## #   `Staff Hours` <chr>, ADA <lgl>, `ADA Notes` <chr>, `Free Crossover` <lgl>,
    ## #   `North South Street` <chr>, `East West Street` <chr>, Corner <chr>,
    ## #   `Entrance Latitude` <dbl>, `Entrance Longitude` <dbl>,
    ## #   `Station Location` <chr>, `Entrance Location` <chr>, and abbreviated …

``` r
# clean the data and convert "entry" from char to logical.
NYC_Transit <- NYC_Transit %>% 
  janitor::clean_names() %>% 
  select(line, station_name, station_latitude, station_longitude,
         route1:route11, entry, vending, entrance_type, ada) %>% 
  mutate(entry = recode(entry, 'YES' = TRUE, 'NO' = FALSE))
# show the first several lines of the cleaned data
head(NYC_Transit)
```

    ## # A tibble: 6 × 19
    ##   line  stati…¹ stati…² stati…³ route1 route2 route3 route4 route5 route6 route7
    ##   <chr> <chr>     <dbl>   <dbl> <chr>  <chr>  <chr>  <chr>  <chr>  <chr>  <chr> 
    ## 1 4 Av… 25th St    40.7   -74.0 R      <NA>   <NA>   <NA>   <NA>   <NA>   <NA>  
    ## 2 4 Av… 25th St    40.7   -74.0 R      <NA>   <NA>   <NA>   <NA>   <NA>   <NA>  
    ## 3 4 Av… 36th St    40.7   -74.0 N      R      <NA>   <NA>   <NA>   <NA>   <NA>  
    ## 4 4 Av… 36th St    40.7   -74.0 N      R      <NA>   <NA>   <NA>   <NA>   <NA>  
    ## 5 4 Av… 36th St    40.7   -74.0 N      R      <NA>   <NA>   <NA>   <NA>   <NA>  
    ## 6 4 Av… 45th St    40.6   -74.0 R      <NA>   <NA>   <NA>   <NA>   <NA>   <NA>  
    ## # … with 8 more variables: route8 <dbl>, route9 <dbl>, route10 <dbl>,
    ## #   route11 <dbl>, entry <lgl>, vending <chr>, entrance_type <chr>, ada <lgl>,
    ## #   and abbreviated variable names ¹​station_name, ²​station_latitude,
    ## #   ³​station_longitude

``` r
skimr::skim(NYC_Transit)
```

|                                                  |             |
|:-------------------------------------------------|:------------|
| Name                                             | NYC_Transit |
| Number of rows                                   | 1868        |
| Number of columns                                | 19          |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |             |
| Column type frequency:                           |             |
| character                                        | 11          |
| logical                                          | 2           |
| numeric                                          | 6           |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |             |
| Group variables                                  | None        |

Data summary

**Variable type: character**

| skim_variable | n_missing | complete_rate | min | max | empty | n_unique | whitespace |
|:--------------|----------:|--------------:|----:|----:|------:|---------:|-----------:|
| line          |         0 |          1.00 |   5 |  17 |     0 |       36 |          0 |
| station_name  |         0 |          1.00 |   4 |  39 |     0 |      356 |          0 |
| route1        |         0 |          1.00 |   1 |   2 |     0 |       24 |          0 |
| route2        |       848 |          0.55 |   1 |   2 |     0 |       20 |          0 |
| route3        |      1374 |          0.26 |   1 |   2 |     0 |       18 |          0 |
| route4        |      1547 |          0.17 |   1 |   1 |     0 |       13 |          0 |
| route5        |      1630 |          0.13 |   1 |   1 |     0 |       12 |          0 |
| route6        |      1741 |          0.07 |   1 |   1 |     0 |        7 |          0 |
| route7        |      1788 |          0.04 |   1 |   2 |     0 |        7 |          0 |
| vending       |         0 |          1.00 |   2 |   3 |     0 |        2 |          0 |
| entrance_type |         0 |          1.00 |   4 |   9 |     0 |        7 |          0 |

**Variable type: logical**

| skim_variable | n_missing | complete_rate | mean | count               |
|:--------------|----------:|--------------:|-----:|:--------------------|
| entry         |         0 |             1 | 0.94 | TRU: 1753, FAL: 115 |
| ada           |         0 |             1 | 0.25 | FAL: 1400, TRU: 468 |

**Variable type: numeric**

| skim_variable     | n_missing | complete_rate |   mean |   sd |     p0 |    p25 |    p50 |    p75 |   p100 | hist  |
|:------------------|----------:|--------------:|-------:|-----:|-------:|-------:|-------:|-------:|-------:|:------|
| station_latitude  |         0 |          1.00 |  40.73 | 0.07 |  40.58 |  40.69 |  40.73 |  40.77 |  40.90 | ▂▅▇▃▂ |
| station_longitude |         0 |          1.00 | -73.94 | 0.06 | -74.03 | -73.99 | -73.96 | -73.91 | -73.76 | ▇▆▃▂▁ |
| route8            |      1820 |          0.03 |   2.98 | 1.94 |   1.00 |   1.00 |   4.00 |   5.00 |   5.00 | ▇▁▁▂▇ |
| route9            |      1840 |          0.01 |   2.54 | 1.17 |   2.00 |   2.00 |   2.00 |   2.00 |   5.00 | ▇▁▁▁▂ |
| route10           |      1845 |          0.01 |   3.00 | 0.00 |   3.00 |   3.00 |   3.00 |   3.00 |   3.00 | ▁▁▇▁▁ |
| route11           |      1845 |          0.01 |   7.00 | 0.00 |   7.00 |   7.00 |   7.00 |   7.00 |   7.00 | ▁▁▇▁▁ |

Write a short paragraph about this dataset – explain briefly what
variables the dataset contains, describe your data cleaning steps so
far, and give the dimension (rows x columns) of the resulting dataset.
Are these data tidy?

Answer:

This dataset contains 19 variables, including 11 character variables,
e.g. line, 6 numeric variables, e.g. station latitude, station
longitude, and 2 logical variables, e.g. ada, entry.

After I read in the data, I used clean_names() to make the all the
variables name lowercase, and only select line, station_name,
station_latitude, station_longitude, route, entry, vending,
entrance_type, ada variables. Then I mutated the entry variable from
character to logical type.

There are 1868 rows and 19 columns. The data cannot be considered tidy,
since the route variable spread over the table, and does not have its
own column.

### b)

Answer the following questions using these data:

How many distinct stations are there? Note that stations are identified
both by name and by line (e.g. 125th St 8th Avenue; 125st Broadway;
125st Lenox); the distinct function may be useful here.

``` r
NYC_Transit %>% 
  select(station_name, line) %>% 
  distinct() %>% 
  count()
```

    ## # A tibble: 1 × 1
    ##       n
    ##   <int>
    ## 1   465

Answer: 465 distinct stations.

How many stations are ADA compliant?

``` r
NYC_Transit %>% 
  select(station_name, line, ada) %>%
  filter(ada == TRUE) %>% 
  distinct() %>% 
  count()
```

    ## # A tibble: 1 × 1
    ##       n
    ##   <int>
    ## 1    84

Answer: 84 distinct stations are ADA compliant.

What proportion of station entrances / exits without vending allow
entrance?

``` r
# number of station without vending
Non_vending <-
  NYC_Transit %>% 
  select(station_name, line, vending) %>%
  filter(vending == "NO") %>% 
  distinct() %>% 
  count()
# proportion
Non_vending / 465
```

    ##           n
    ## 1 0.2129032

Answer: 21.29% proportion of station entrances / exits without vending
allow entrance.

Reformat data so that route number and route name are distinct
variables. How many distinct stations serve the A train?

``` r
# converted route8-route11 to character variable
# made the route1 to route11 to be a new route_number variable while the value # under each route made a new value variable route_name
# deleted the prefix of route1 to route11 in order to only contain numbers
# removed all the rows which contains NA in route_name
NYC_Transit_tidy <- NYC_Transit %>% 
  mutate(route8 = as.character(route8), route9 = as.character(route9),
         route10 = as.character(route10), route11 = as.character(route11)) %>% 
  pivot_longer(route1:route11, names_to = "route_number",
               names_prefix = "route", values_to = "route_name") %>% 
  drop_na(route_name)

NYC_Transit_tidy %>% 
  select(station_name, line, route_name) %>%
  filter(route_name == "A") %>% 
  distinct() %>% 
  count()
```

    ## # A tibble: 1 × 1
    ##       n
    ##   <int>
    ## 1    60

Answer: 60 distinct stations serve the A train.

Of the stations that serve the A train, how many are ADA compliant?

``` r
NYC_Transit_tidy %>% 
  select(station_name, line, route_name, ada) %>%
  filter(route_name == "A" & ada == TRUE) %>% 
  distinct() %>% 
  count()
```

    ## # A tibble: 1 × 1
    ##       n
    ##   <int>
    ## 1    17

Answer: Of the stations that serve the A train, 17 distinct stations are
ADA compliant.

## Problem 2

This problem uses the Mr. Trash Wheel dataset, available as an Excel
file on the course website.

Read and clean the Mr. Trash Wheel sheet:

specify the sheet in the Excel file and to omit non-data entries (rows
with notes / figures; columns containing notes) using arguments in
read_excel

use reasonable variable names

omit rows that do not include dumpster-specific data

round the number of sports balls to the nearest integer and converts the
result to an integer variable (using as.integer)
